---
- name: Déploiement de l app web
  hosts: aws_ec2
  become: yes
  tasks:
    - name: apt update
      apt:
        update_cache: yes

    - name: Installation des dependances
      apt:
        name:
          - git
          - nginx
          - python3
          - python3-pip
        state: present

    - name: Cloner le repo git de l app
      git:
        repo: "https://github.com/Nicolas-Tondeur/Exercice-2_cours-git.git"
        dest: /var/www/app
        version: dev

    - name: Configuration Nginx
      copy:
        dest: /etc/nginx/sites-available/app
        content: |
          server {
              listen 80;
              root /var/www/app;
              index todo-app/Contact.html;
              server_name _;
          }
      notify: Restart nginx

    - name: Activation de la config Nginx
      file:
        src: /etc/nginx/sites-available/app
        dest: /etc/nginx/sites-enabled/app
        state: link
        force: yes

    - name: Desactivation du site par défaut de Nginx
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Restart nginx

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted