name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Récupération du code
      uses: actions/checkout@v4

    - name: Installation de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Installation d'Ansible
      run: pip install ansible

    - name: Création de la clé SSH AWS
      run: |
        echo "${{ secrets.AWS_SSH_KEY }}" > aws_key.pem
        chmod 600 aws_key.pem

    - name: Lancement du playbook Ansible
      run: |
        # Nous modifions le fichier d'inventaire pour qu'il pointe vers la clé créée
        sed -i 's|ansible_ssh_private_key_file=.*|ansible_ssh_private_key_file=./aws_key.pem|' AWS/inventory_aws.ini
        ansible-playbook -i AWS/inventory_aws.ini AWS/deploy.yml

    - name: Suppression de la clé SSH
      if: always() 
      run: rm -f aws_key.pem