name: Python application test

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Récupération du code
      uses: actions/checkout@v4

    - name: Installation de Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Installation des dépendances
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        # Installe les dépendances du projet s'il y a un fichier requirements.txt dans le sous-dossier
        if [ -f todo-app/requirements.txt ]; then pip install -r todo-app/requirements.txt; fi
      
    - name: Lancer les tests avec pytest
      # On se place dans le dossier contenant le code source pour que les imports fonctionnent
      working-directory: ./todo-app
      run: |
        python -m pytest